namespace CarVendor.Web.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class v000 : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.CarCategories", "EngineCapacity", c => c.Int(nullable: false));
            AddColumn("dbo.CarCategories", "TransfersNo", c => c.Int(nullable: false));
            AddColumn("dbo.CarCategories", "CylindersNo", c => c.Int(nullable: false));
            AddColumn("dbo.CarCategories", "CastingsNo", c => c.Int(nullable: false));
            AddColumn("dbo.CarCategories", "ElectronicFuelInjection", c => c.Boolean(nullable: false));
            AddColumn("dbo.CarCategories", "MaximumTorque", c => c.String());
            AddColumn("dbo.CarCategories", "EnginePower", c => c.String());
            AddColumn("dbo.CarCategories", "Acceleration", c => c.Int(nullable: false));
            AddColumn("dbo.CarCategories", "TractionType", c => c.String());
            AddColumn("dbo.CarCategories", "SeatsNo", c => c.Int(nullable: false));
            AddColumn("dbo.CarCategories", "DoorsNo", c => c.Int(nullable: false));
            AddColumn("dbo.CarCategories", "AvgFuelConsumption", c => c.Int(nullable: false));
            AddColumn("dbo.CarCategories", "FuelTankCapacity", c => c.Int(nullable: false));
            AddColumn("dbo.CarCategories", "GroundClearance", c => c.Int(nullable: false));
            AddColumn("dbo.CarCategories", "MaxSpeed", c => c.Int(nullable: false));
            AddColumn("dbo.CarCategories", "FuelRecommended", c => c.String());
            AddColumn("dbo.CarCategories", "DriverAirbags", c => c.Boolean(nullable: false));
            AddColumn("dbo.CarCategories", "FrontPassengerAirbags", c => c.Boolean(nullable: false));
            AddColumn("dbo.CarCategories", "ElectricChairs", c => c.Boolean(nullable: false));
            AddColumn("dbo.CarCategories", "BrakeSystemABS", c => c.Boolean(nullable: false));
            AddColumn("dbo.CarCategories", "ElectronicBrakeDistribution", c => c.Boolean(nullable: false));
            AddColumn("dbo.CarCategories", "ElectronicBalanceProgram", c => c.Boolean(nullable: false));
            AddColumn("dbo.CarCategories", "AntitheftAlarmSystem", c => c.Boolean(nullable: false));
            AddColumn("dbo.CarCategories", "ImmobilizerSystemAgainstTheft", c => c.Boolean(nullable: false));
            AddColumn("dbo.CarCategories", "SportRims", c => c.Boolean(nullable: false));
            AddColumn("dbo.CarCategories", "RimSize", c => c.Int(nullable: false));
            AddColumn("dbo.CarCategories", "FrontFogLanterns", c => c.Boolean(nullable: false));
            AddColumn("dbo.CarCategories", "BackFogLanterns", c => c.Boolean(nullable: false));
            AddColumn("dbo.CarCategories", "BackCleaners", c => c.Boolean(nullable: false));
            AddColumn("dbo.CarCategories", "ElectricSideMirrors", c => c.Boolean(nullable: false));
            AddColumn("dbo.CarCategories", "ElectricallyFoldingSideMirrors", c => c.Boolean(nullable: false));
            AddColumn("dbo.CarCategories", "SideMirrorsSignals", c => c.Boolean(nullable: false));
            AddColumn("dbo.CarCategories", "XenonBulbsLighting", c => c.Boolean(nullable: false));
            AddColumn("dbo.CarCategories", "HeadlampWipers", c => c.Boolean(nullable: false));
            AddColumn("dbo.CarCategories", "SensitiveHeadlamps", c => c.Boolean(nullable: false));
            AddColumn("dbo.CarCategories", "HeadlampControl", c => c.Boolean(nullable: false));
            AddColumn("dbo.CarCategories", "HeadlampLightingLED", c => c.Boolean(nullable: false));
            AddColumn("dbo.CarCategories", "TaillightsLightingLED", c => c.Boolean(nullable: false));
            AddColumn("dbo.CarCategories", "BackSpoiler", c => c.Boolean(nullable: false));
            AddColumn("dbo.CarCategories", "IntelligentParkingSystem", c => c.Boolean(nullable: false));
            AddColumn("dbo.CarCategories", "SoundSystem", c => c.Boolean(nullable: false));
            AddColumn("dbo.CarCategories", "CDDriver", c => c.Boolean(nullable: false));
            AddColumn("dbo.CarCategories", "AUXPort", c => c.Boolean(nullable: false));
            AddColumn("dbo.CarCategories", "USBPort", c => c.Boolean(nullable: false));
            AddColumn("dbo.CarCategories", "Bluetooth", c => c.Boolean(nullable: false));
            AddColumn("dbo.CarCategories", "FrontHeadrests", c => c.Boolean(nullable: false));
            AddColumn("dbo.CarCategories", "RearHeadrests", c => c.Boolean(nullable: false));
            AddColumn("dbo.CarCategories", "ElectricWindshield", c => c.Boolean(nullable: false));
            AddColumn("dbo.CarCategories", "ElectricRearGlass", c => c.Boolean(nullable: false));
            AddColumn("dbo.CarCategories", "OneTouchGlassControl", c => c.Boolean(nullable: false));
            AddColumn("dbo.CarCategories", "RemoteControlToLockAndOpenDoors", c => c.Boolean(nullable: false));
            AddColumn("dbo.CarCategories", "DriverHeightControl", c => c.Boolean(nullable: false));
            AddColumn("dbo.CarCategories", "LeatherBrushes", c => c.Boolean(nullable: false));
            AddColumn("dbo.CarCategories", "EngineStartStopButtonSystem", c => c.Boolean(nullable: false));
            AddColumn("dbo.CarCategories", "Sunroof", c => c.Boolean(nullable: false));
            AddColumn("dbo.CarCategories", "ElectricSunroof", c => c.Boolean(nullable: false));
            AddColumn("dbo.CarCategories", "BackCamera", c => c.Boolean(nullable: false));
            AddColumn("dbo.CarCategories", "ComputerTrips", c => c.Boolean(nullable: false));
            AddColumn("dbo.CarCategories", "SteeringWheelType", c => c.Boolean(nullable: false));
            AddColumn("dbo.CarCategories", "ControllableSteeringWheel", c => c.Boolean(nullable: false));
            AddColumn("dbo.CarCategories", "ControlTheSoundSystemOfTheSteeringWheel", c => c.Boolean(nullable: false));
            AddColumn("dbo.CarCategories", "CruiseControl", c => c.Boolean(nullable: false));
            AddColumn("dbo.CarCategories", "LeatherSteeringWheel", c => c.Boolean(nullable: false));
            AddColumn("dbo.CarCategories", "LeatherTransmission", c => c.Boolean(nullable: false));
            AddColumn("dbo.CarCategories", "FrontDoorStorage", c => c.Boolean(nullable: false));
            AddColumn("dbo.CarCategories", "BackDoorStorageAreas", c => c.Boolean(nullable: false));
            AddColumn("dbo.CarCategories", "PossibilityToFoldBackSeats", c => c.Boolean(nullable: false));
            AddColumn("dbo.CarCategories", "Lighter", c => c.Boolean(nullable: false));
            AddColumn("dbo.CarCategories", "MobileAshtray", c => c.Boolean(nullable: false));
            AddColumn("dbo.CarCategories", "CentralDoorLock", c => c.Boolean(nullable: false));
            AddColumn("dbo.CarCategories", "AlarmSoundWhenTheCarIsNotClosed", c => c.Boolean(nullable: false));
            AddColumn("dbo.CarCategories", "FrontCupHolder", c => c.Boolean(nullable: false));
            AddColumn("dbo.CarCategories", "BackCupHolder", c => c.Boolean(nullable: false));
            AddColumn("dbo.CarCategories", "FrontArmrest", c => c.Boolean(nullable: false));
            AddColumn("dbo.CarCategories", "AirConditionedFrontArmrest", c => c.Boolean(nullable: false));
            AddColumn("dbo.CarCategories", "BackArmrest", c => c.Boolean(nullable: false));
            AddColumn("dbo.CarCategories", "BackTrunkCover", c => c.Boolean(nullable: false));
            AddColumn("dbo.CarCategories", "FrontStorageDrawer", c => c.Boolean(nullable: false));
            AddColumn("dbo.CarCategories", "PowerOutlet", c => c.Boolean(nullable: false));
            AddColumn("dbo.CarCategories", "BackOutletPowerOutlet", c => c.Boolean(nullable: false));
            AddColumn("dbo.CarCategories", "BackWipers", c => c.Boolean(nullable: false));
            AddColumn("dbo.CarCategories", "RainSensitiveWindshieldWipers", c => c.Boolean(nullable: false));
            AddColumn("dbo.CarCategories", "BackLight", c => c.Boolean(nullable: false));
            AddColumn("dbo.CarCategories", "SensitiveHeadlampsForLighting", c => c.Boolean(nullable: false));
            AddColumn("dbo.CarCategories", "BackTrunkSpace", c => c.Boolean(nullable: false));
            AddColumn("dbo.CarCategories", "BackSeatBelt", c => c.Boolean(nullable: false));
        }
        
        public override void Down()
        {
            DropColumn("dbo.CarCategories", "BackSeatBelt");
            DropColumn("dbo.CarCategories", "BackTrunkSpace");
            DropColumn("dbo.CarCategories", "SensitiveHeadlampsForLighting");
            DropColumn("dbo.CarCategories", "BackLight");
            DropColumn("dbo.CarCategories", "RainSensitiveWindshieldWipers");
            DropColumn("dbo.CarCategories", "BackWipers");
            DropColumn("dbo.CarCategories", "BackOutletPowerOutlet");
            DropColumn("dbo.CarCategories", "PowerOutlet");
            DropColumn("dbo.CarCategories", "FrontStorageDrawer");
            DropColumn("dbo.CarCategories", "BackTrunkCover");
            DropColumn("dbo.CarCategories", "BackArmrest");
            DropColumn("dbo.CarCategories", "AirConditionedFrontArmrest");
            DropColumn("dbo.CarCategories", "FrontArmrest");
            DropColumn("dbo.CarCategories", "BackCupHolder");
            DropColumn("dbo.CarCategories", "FrontCupHolder");
            DropColumn("dbo.CarCategories", "AlarmSoundWhenTheCarIsNotClosed");
            DropColumn("dbo.CarCategories", "CentralDoorLock");
            DropColumn("dbo.CarCategories", "MobileAshtray");
            DropColumn("dbo.CarCategories", "Lighter");
            DropColumn("dbo.CarCategories", "PossibilityToFoldBackSeats");
            DropColumn("dbo.CarCategories", "BackDoorStorageAreas");
            DropColumn("dbo.CarCategories", "FrontDoorStorage");
            DropColumn("dbo.CarCategories", "LeatherTransmission");
            DropColumn("dbo.CarCategories", "LeatherSteeringWheel");
            DropColumn("dbo.CarCategories", "CruiseControl");
            DropColumn("dbo.CarCategories", "ControlTheSoundSystemOfTheSteeringWheel");
            DropColumn("dbo.CarCategories", "ControllableSteeringWheel");
            DropColumn("dbo.CarCategories", "SteeringWheelType");
            DropColumn("dbo.CarCategories", "ComputerTrips");
            DropColumn("dbo.CarCategories", "BackCamera");
            DropColumn("dbo.CarCategories", "ElectricSunroof");
            DropColumn("dbo.CarCategories", "Sunroof");
            DropColumn("dbo.CarCategories", "EngineStartStopButtonSystem");
            DropColumn("dbo.CarCategories", "LeatherBrushes");
            DropColumn("dbo.CarCategories", "DriverHeightControl");
            DropColumn("dbo.CarCategories", "RemoteControlToLockAndOpenDoors");
            DropColumn("dbo.CarCategories", "OneTouchGlassControl");
            DropColumn("dbo.CarCategories", "ElectricRearGlass");
            DropColumn("dbo.CarCategories", "ElectricWindshield");
            DropColumn("dbo.CarCategories", "RearHeadrests");
            DropColumn("dbo.CarCategories", "FrontHeadrests");
            DropColumn("dbo.CarCategories", "Bluetooth");
            DropColumn("dbo.CarCategories", "USBPort");
            DropColumn("dbo.CarCategories", "AUXPort");
            DropColumn("dbo.CarCategories", "CDDriver");
            DropColumn("dbo.CarCategories", "SoundSystem");
            DropColumn("dbo.CarCategories", "IntelligentParkingSystem");
            DropColumn("dbo.CarCategories", "BackSpoiler");
            DropColumn("dbo.CarCategories", "TaillightsLightingLED");
            DropColumn("dbo.CarCategories", "HeadlampLightingLED");
            DropColumn("dbo.CarCategories", "HeadlampControl");
            DropColumn("dbo.CarCategories", "SensitiveHeadlamps");
            DropColumn("dbo.CarCategories", "HeadlampWipers");
            DropColumn("dbo.CarCategories", "XenonBulbsLighting");
            DropColumn("dbo.CarCategories", "SideMirrorsSignals");
            DropColumn("dbo.CarCategories", "ElectricallyFoldingSideMirrors");
            DropColumn("dbo.CarCategories", "ElectricSideMirrors");
            DropColumn("dbo.CarCategories", "BackCleaners");
            DropColumn("dbo.CarCategories", "BackFogLanterns");
            DropColumn("dbo.CarCategories", "FrontFogLanterns");
            DropColumn("dbo.CarCategories", "RimSize");
            DropColumn("dbo.CarCategories", "SportRims");
            DropColumn("dbo.CarCategories", "ImmobilizerSystemAgainstTheft");
            DropColumn("dbo.CarCategories", "AntitheftAlarmSystem");
            DropColumn("dbo.CarCategories", "ElectronicBalanceProgram");
            DropColumn("dbo.CarCategories", "ElectronicBrakeDistribution");
            DropColumn("dbo.CarCategories", "BrakeSystemABS");
            DropColumn("dbo.CarCategories", "ElectricChairs");
            DropColumn("dbo.CarCategories", "FrontPassengerAirbags");
            DropColumn("dbo.CarCategories", "DriverAirbags");
            DropColumn("dbo.CarCategories", "FuelRecommended");
            DropColumn("dbo.CarCategories", "MaxSpeed");
            DropColumn("dbo.CarCategories", "GroundClearance");
            DropColumn("dbo.CarCategories", "FuelTankCapacity");
            DropColumn("dbo.CarCategories", "AvgFuelConsumption");
            DropColumn("dbo.CarCategories", "DoorsNo");
            DropColumn("dbo.CarCategories", "SeatsNo");
            DropColumn("dbo.CarCategories", "TractionType");
            DropColumn("dbo.CarCategories", "Acceleration");
            DropColumn("dbo.CarCategories", "EnginePower");
            DropColumn("dbo.CarCategories", "MaximumTorque");
            DropColumn("dbo.CarCategories", "ElectronicFuelInjection");
            DropColumn("dbo.CarCategories", "CastingsNo");
            DropColumn("dbo.CarCategories", "CylindersNo");
            DropColumn("dbo.CarCategories", "TransfersNo");
            DropColumn("dbo.CarCategories", "EngineCapacity");
        }
    }
}
