// <auto-generated />
namespace CarVendor.data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class v012 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v012));
        
        string IMigrationMetadata.Id
        {
            get { return "201907141400297_v0.1.2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
