// <auto-generated />
namespace CarVendor.data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class v001 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v001));
        
        string IMigrationMetadata.Id
        {
            get { return "201907070339298_v0.0.1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
