// <auto-generated />
namespace CarVendor.data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class m31 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(m31));
        
        string IMigrationMetadata.Id
        {
            get { return "201907211113141_m31"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
