// <auto-generated />
namespace CarVendor.data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddPaymentType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddPaymentType));
        
        string IMigrationMetadata.Id
        {
            get { return "202003091606222_Add Payment Type"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
