// <auto-generated />
namespace CarVendor.data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CallBackv01 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CallBackv01));
        
        string IMigrationMetadata.Id
        {
            get { return "202001200801521_CallBack-v-0.1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
